spring.application.name=backend
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://db:3306/app_db}
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=dev

# Flowable configuration
flowable.database.schema-update=true
flowable.common.app.idm.enabled=true
flowable.common.app.idm.admin.userid=admin
flowable.common.app.idm.admin.password=admin
flowable.common.app.idm.admin.first-name=Admin
flowable.common.app.idm.admin.last-name=User
flowable.common.app.idm.ldap.enabled=false
flowable.process.async-executor-activate=false

spring.sql.init.mode=never
spring.sql.init.schema-locations=
spring.sql.init.data-locations=

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Secret for jwt token generation (for development only, do not use in production)
security.jwt.secret=7U/BAH71JEsuiKluGpwIWwtM4Vna9ORwKgtlQBknGOg=
security.jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Drools RuleUnit configuration
kie.scan.interval=5
kie.server.controller-user=admin
kie.server.controller-password=admin

# Spring component scan
spring.main.scan-base-packages=org.spftech.backend

# Logging for Drools
logging.level.org.drools=DEBUG
logging.level.org.kie=DEBUG
